variables:
  TARGET_BRANCH: main
  UV_VERSION: "0.9"
  PYTHON_VERSION: "3.12"
  BASE_LAYER: bookworm-slim
  QUALITY_REPORT: "code-quality-report.json"
  TEST_REPORT: "test-report.xml"
  COVERAGE_REPORT: "coverage-report.xml"
  # GitLab CI creates a separate mountpoint for the build directory,
  # so we need to copy instead of using hard links.
  UV_LINK_MODE: copy

stages:
  - build
  - test
  - publish

uv:
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$BASE_LAYER
  stage: build
  variables:
    UV_CACHE_DIR: .uv-cache
  cache:
    - key:
        files:
          - uv.lock
      paths:
        - $UV_CACHE_DIR
  script:
    - uv sync --frozen
    - uv cache prune --ci

lint:
  extends: uv
  stage: test
  script:
    - uv run ruff check --output-format=gitlab > $QUALITY_REPORT
  artifacts:
    reports:
      codequality: $QUALITY_REPORT

typecheck:
  extends: uv
  stage: test
  script:
    - uv run ty check src

pytest:
  extends: uv
  stage: test
  script:
    - uv run pytest -v --junitxml=$TEST_REPORT
      --cov=ml_tools --cov-report=term-missing --cov-report=xml:$COVERAGE_REPORT
      --cov-fail-under=80
  artifacts:
    reports:
      junit: $TEST_REPORT
      coverage_report:
        coverage_format: cobertura
        path: $COVERAGE_REPORT

pages:
  extends: uv
  stage: publish
  rules:
    - if: "$CI_COMMIT_BRANCH == $TARGET_BRANCH"
  script:
    - uv run mkdocs build --strict
  artifacts:
    paths:
      - site
  pages: true
