[project]
name = "machina"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "pyqt6>=6.9.1",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.5",
]

[project.scripts]
machina = "machina:main"

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"

[tool.ruff.format]
line-ending = "auto"

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
